# Generated by Django 2.0.2 on 2018-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180315_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo_credit',
            field=models.CharField(default='', max_length=100),
        ),
    ]
