# Generated by Django 2.0.2 on 2018-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_artist_photo_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instrument',
            field=models.CharField(default='', max_length=50),
        ),
    ]
