# Generated by Django 2.0.2 on 2018-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_artist_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('tickets_schwanengesang', models.PositiveIntegerField(default=0)),
                ('tickets_winterreise', models.PositiveIntegerField(default=0)),
                ('tickets_quartettimkonzert', models.PositiveIntegerField(default=0)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
