# Generated by Django 2.0.2 on 2018-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ticketreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='anrede',
            field=models.IntegerField(choices=[(1, 'Herr'), (2, 'Frau')], default=1),
        ),
    ]
