# Generated by Django 2.0.2 on 2018-03-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
