# Generated by Django 2.0.2 on 2018-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mailtemplate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='hausnummer',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='ort',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='plz',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='strasse',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='titel',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
