# Generated by Django 2.0.2 on 2018-03-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180322_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='tickets_quartettimkonzert_erm',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='tickets_schwanengesang_erm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='tickets_winterreise_erm',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='tickets_quartettimkonzert',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='tickets_schwanengesang',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='tickets_winterreise',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
