# Generated by Django 2.0.2 on 2018-03-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180323_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='rang',
            field=models.IntegerField(default=0),
        ),
    ]
