# Generated by Django 2.0.2 on 2018-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_gast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressum', models.TextField()),
                ('contact', models.EmailField(max_length=254)),
                ('disclaimer', models.TextField()),
            ],
        ),
    ]
