# Generated by Django 2.0.2 on 2018-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreservation',
            name='tickets_quartettimkonzert_erm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='tickets_winterreise_erm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketreservation',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
