# Generated by Django 2.0.2 on 2018-04-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ticketreservation_tickets_summe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='nachricht',
            field=models.TextField(blank=True, default=''),
        ),
    ]
