# Generated by Django 2.0.2 on 2018-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_ticketreservation_nachricht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreservation',
            name='anrede',
            field=models.IntegerField(choices=[(1, 'Herr'), (2, 'Frau'), (3, '—')], default=1),
        ),
    ]
