# Generated by Django 2.0.2 on 2018-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180406_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.IntegerField(choices=[(1, 'Herr'), (2, 'Frau'), (3, '—')], default=1)),
                ('titel', models.CharField(blank=True, default='', max_length=15)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('strasse', models.CharField(default='', max_length=50)),
                ('hausnummer', models.CharField(default='', max_length=4)),
                ('plz', models.CharField(default='', max_length=5)),
                ('ort', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(default='', max_length=20)),
                ('alter', models.PositiveIntegerField(default=None)),
                ('stimmfach', models.IntegerField(choices=[(1, 'Sopran'), (2, 'Alt'), (3, 'Tenor'), (4, 'Bass'), (5, '—')], default=1)),
            ],
        ),
    ]
