# Generated by Django 2.0.2 on 2019-03-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_concert_ticket_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='group',
            field=models.CharField(default='pve', max_length=100, null=True),
        ),
    ]
