# Generated by Django 2.0.2 on 2019-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_ticketreservation2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation2019',
            name='tickets_gesamtpaket',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
